### ISSUE TITLE
Regression: Internal Server Error(s) when creating builds via GraphQL API

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-docs#966] opened 2022-01-17 09:26 UTC
In the past few days creating new builds via GraphQL API results a nondescript `Internal Server Error(s) while executing query`.

Looks like recent refactoring of API schema (#425, moving from `github*` parameter names to `owner*`) has left some things in a broken state. Unfortunately the error message is intentionally opaque, so only Cirrus staff can help with further troubleshooting.

The following query with similar payload was working correctly before (last known successful usage: January 14).

Sample API query:

```graphql
mutation ScheduleCustomBuild($config: String!,
                             $repo: ID!,
                             $branch: String!,
                             $mutation_id: String!) {
    createBuild(
        input: {
            repositoryId: $repo,
            branch: $branch,
            clientMutationId: $mutation_id,
            configOverride: $config
        }
    ) {
        build {
            id
            status
        }
    }
}
```

Parameters:

```yaml
repo: '4749235174244352'
branch: master
mutation_id: cirrus-run job 385065
config: |-
  test_task:
    name: Simple noop task
    container:
      image: debian:stable-slim
    test_script: echo Hello World
```

Response:

```json
{
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query",
      "locations": []
    }
  ],
  "data": {
    "createBuild": null
  }
}
```

**Comment by fkorotkov** [comment] 2022-01-25 16:27
Hey @sio, sorry for the inconveniences. I was not able to find the root cause of the transient issue you've seen but I made a change to improve error reporting so next time it won't be just `"Internal Server Error(s) while executing query"`. Will close the issue for now. Please reopen if you'll see error again.

**Closed by fkorotkov** 2022-01-25 16:27 UTC
