### ISSUE TITLE
Provide compute platform and region as CIRRUS_* variables.

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#951] opened 2021-12-19 23:46 UTC
Most cloud providers price have cheap or free intra region traffic, more expensive inter-region traffic and even more expensive traffic to other cloud providers.  Containers will often, as e.g. the case with google's artifact registry, be in a region. 

To minimize costs it'd be useful to change the the reference of a docker image to the provider and region a container runs in. Having e.g. CIRRUS_REGION, CIRRUS_MULTI_REGION could allow specifying a container reference like

```yaml
task:
  ...
  container:
    image: ${CIRRUS_MULTI_REGION}-docker.pkg.dev/${GCP_PROJECT}/${GCP_REPO}/my-beautiful-container:tag
```
when mirroring images across the three [multi-regions](https://cloud.google.com/artifact-registry/docs/repo-locations#location-mr) and it could work similarly if one used "plain" regions.

It's a bit less obvious (and not as crucial, given that it can be inferred from the container arch) how to make the same `image: ` work for both gcp and aws, given the restrictions of the yaml format. But it still seems useful to provide the compute provider as a CIRRUS_ variable. I haven't tried yet, but if variable references themselves interpolate variables, it could actually be doable using something like:

```yaml
  env: 
    CONTAINER_REPO_AWS: https://${AWS_ACCOUNT}.dkr.ecr.${CIRRUS_REGIONS}.amazonaws.com
    CONTAINER_REPO_GCP: ${CIRRUS_MULTI_REGION}-docker.pkg.dev/${GCP_PROJECT}/${REPO_NAME}
  container:
    image: ${CONTAINER_REPO_${CIRRUS_PROVIDER}}/my-beautiful-container:tag
```

**Comment by fkorotkov** [comment] 2021-12-20 15:07
Whike digging a bit into the code and thinking about this issue I realized that for your use case information about the region where Cirrus CI will run a task is required during parsing phase. Where internally we have several microservices that "manage" instances for a given provider and it's responsibility of these services to choose where to schedule a task. We can make these services to set such environment variables so they are available during the execution phase of the task but it will be too late for your use case.

Another thought I had is that this information is needed only for instances [*"Managed by us"*](https://cirrus-ci.org/guide/writing-tasks/#execution-environment). For instances *"Managed by you"*, customers have full control over where and how to schedule tasks: either in a single zone or in multiple zones.

Right now Cirrus CI uses three cloud providers for *"Managed by us"* instances:

* For `macos_instance`s [both datacenters of Mac Mini Vault](https://www.macminivault.com/datacenter/) are used. 
* For `arm_container`s AWS's `us-east-2` region is used.
* For everything else GCP's `us-central1` region is used.

I don't think we are going to change the way we are running *"Managed by us"* instances for one simple reason: we are trying to make Cirrus CI as cost efficient as possible and for that reason Cirrus CI is configured to store caches and logs in a single region so we don't pay for replication. We do use as many zones within the region as possible for better availability though. **Note:** that is doesn't mean we are not going to run the orchestration part of Cirrus CI in multiple regions, just the part where containers and VMs are scheduled and caches/logs are stored.

So I think for the given time we can simply document how and where Cirrus CI is running *"Managed by us"* instances like I described above. @anarazel, what do you think?

**Comment by anarazel** [comment] 2021-12-20 21:46
> We can make these services to set such environment variables so they are available during the execution phase of the task but it will be too late for your use case.

I was worried that that might be the case...


> So I think for the given time we can simply document how and where Cirrus CI is running "Managed by us" instances like I described above. @anarazel, what do you think?

Yes, I think that'd address my use-case. It might be worth doing something fancier at some point, but for now...

**Comment by fkorotkov** [comment] 2021-12-21 16:42
>  It might be worth doing something fancier at some point

We are working on some fancy way of distributing artifacts like Docker images regardless of your geo location or cloud presence. Stay tuned!

**Comment by fkorotkov** [comment] 2022-02-04 14:12
Closing the issue since having the variables available during parsing time is not possible at the moment by design.

**Closed by fkorotkov** 2022-02-04 14:12 UTC
Labels: feature
