### ISSUE TITLE
Artifact upload/download very slow for 1000+ files

### ISSUE THREAD

**Issue by bdrewery** [cirruslabs/cirrus-ci-docs#637] opened 2020-05-06 17:01 UTC
# Question

https://cirrus-ci.com/task/4855508010008576
```
always:                                                                                                                        
        bulk_logs_cleanup_script:                                                                                              
                - ( find -x test_bulk/data/logs/bulk ! -name '*.log' ! -name '.poudriere.*' ! -name '*.json' -delete; ) || true
        test_logs_artifacts:
                paths:
                        - "test/*.log"
                        - "test_bulk/data/logs/bulk/**"
                type: text/plain
```
https://api.cirrus-ci.com/v1/task/4855508010008576/logs/test_logs.log

The `test_logs` artifact upload took 4:10 while the rest of the job was just over 6 minutes. 
Downloading the full zip file took several minutes and is only 1.4M zipped and 7.2M unzipped.
In total there are 1688 files and 152 directories.

Is this just an infrastructure/network issue or is it due to the number of files I am uploading? Is there some way I could improve this so it's not nearly doubling the job time? I haven't tried pre-tarring them but given the download time I'm not sure I want to do that either.

**Comment by RDIL** [comment] 2020-05-06 17:04
Not sure why its taking that long, but maybe gzipping it or bzipping it might help?

**Comment by fkorotkov** [comment] 2020-05-06 17:31
It's due to the number of files. Cirrus doesn't zip the artifacts first and unzips on the server side. Instead it uses a single GRPC stream to stream all files to Cirrus. My guess is that most of the 4 minutes time spend creating the files in Google Cloud Storage. Cirrus should probably use batch API for artifacts. Will investigate it.

**Comment by RDIL** [comment] 2020-05-06 17:54
Or compress with brotoli since I hear it has very low file sizes - might help out also

**Comment by fkorotkov** [comment] 2020-05-06 19:19
Batch upload is not supported and only batch updates/deletes/etc. Compressing won't work since you'll still need to decompress and create 1000s of files. 

And storing just the compressed archive won't work since Cirrus supports combining artifacts with the same name from different matrix tasks and Cirrus needs files in that case.

Unfortunately for now the answer to the slowness of uploading many many files is there by design.

**Comment by fkorotkov** [comment] 2022-10-10 19:53
Closing since there is nothing can be done. FYI the uploads became much faster since the time of the issue creation so it might be not as notable nowadays.

**Closed by fkorotkov** 2022-10-10 19:53 UTC
Labels: enhancement, UX
