### ISSUE TITLE
ARM Linux tasks flaking frequently and becoming un-restartable

### ISSUE THREAD

**Issue by armanbilge** [cirruslabs/cirrus-ci-docs#1177] opened 2023-06-15 16:53 UTC
We've happily adopted Cirrus CI for several projects, thanks for supporting OSS!

However, we are starting to have serious issues with the Linux ARM runners.

- Sometimes they may take multiple hours to get scheduled. This is not ideal, but perfectly understandable and fine :)

- Sometimes they don't get scheduled at all and just fail after several hours without even running. Not great, but at least we can restart?

- When they do run, sometimes their networking appears to be completely borked. We frequently get `Caught java.net.SocketException (Connection reset)` when our build tool downloads dependencies.

All of this seems very specific to the Linux ARM runners. ~~I have another repo using Compute Engine ARM runners and those seem better behaved. Should we switch to those?~~ Edit: Hmm, I forgot I had some [similar issues](https://cirrus-ci.com/build/6076428370837504) with those as well 🤔 

Here are several examples.
- https://cirrus-ci.com/build/5284870327369728
- https://cirrus-ci.com/build/4640563962576896
- https://cirrus-ci.com/task/5501184190971904
- https://cirrus-ci.com/task/5078755652141056

Thanks!

**Comment by fkorotkov** [comment] 2023-06-15 18:21
Hey @armanbilge, sorry for the inconveniences. We had some issues this week with `arm_container`s. There was an incident with AWS on Tuesday which escalated [our migration to Google Cloud](https://twitter.com/cirrus_labs/status/1668724692969046017). Unfortunately, the migration wasn't smooth and we hit scaling issues with GKE Autopilot.

As of 12pm EST June 15ht we believe we mitigated all the issue and going forward `arm_container`s will perform even better than before. Motivations for the Migration was that Ampere Atla processors on GCP and more performant than Graviton in terms of speed and costs.

Closing the issue as we believe the issue is mitigated. If you'll notice something sketchy with newly created builds please reopen.

**Closed by fkorotkov** 2023-06-15 18:21 UTC
Labels: bug

**Comment by armanbilge** [comment] 2023-06-16 21:51
We still seem to be having problems, at least related to networking :(

https://cirrus-ci.com/task/4576266557325312

**Comment by armanbilge** [comment] 2023-06-19 19:20
I'm not sure what exactly has happened that caused our ARM jobs to fail with network issues. They were working fine for several weeks before.

I slightly changed our Docker image and it seems to be working now.

**Comment by armanbilge** [comment] 2023-06-19 20:30
Nope, after a few working jobs it seems to have broken again 😕 exact same error.

https://cirrus-ci.com/build/4888547790946304

**Comment by armanbilge** [comment] 2023-06-21 21:16
Cool, I see you are aware of the problems here: https://twitter.com/cirrus_labs/status/1671301666497519616

**Comment by fkorotkov** [comment] 2023-06-21 23:39
We are  still not 100% sure what was the reason of the flakiness. The only similar reports we found was https://github.com/google/gvisor/issues/1515 which is allegedly is fixed.

We've created a new network with hight MTU and also ipv6 capable to fix #969. New tasks created after 16:30 PST on June 21st should be using the new network. Where we ran bunch of tests and were not able to reproduce the issue. So fingers crossed. Please let us know if the issue re-appear and sorry about the inconviniences!

**Comment by armanbilge** [comment] 2023-06-22 15:05
@fkorotkov it was working for a little while, but it just broke again 😕 sorry, and thanks for all your help!

https://cirrus-ci.com/build/5766384076980224

**Comment by armanbilge** [comment] 2023-06-22 23:13
We are removing ARM jobs from our CI matrix for now 😢 

- https://github.com/typelevel/cats-effect/pull/3696

**Comment by armanbilge** [comment] 2023-09-06 19:13
We recently restored ARM and we are still getting these errors.

https://cirrus-ci.com/task/4859101277061120
