### ISSUE TITLE
An ability to manually delete cache

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#740] opened 2020-12-02 22:35 UTC
# Description

Kind of button to delete project's cache in CI.

# Context

I have wrong cache, I don't want to use custom keys, and now I have "cache hit" even after changing `populate_script`.

# Anything Else

```yaml
  nodenv_cache:
    folder: $HOME/.nodenv
    populate_script:
      - git clone https://github.com/nodenv/nodenv.git ~/.nodenv

      - source ~/.bashrc

      ## https://github.com/nodenv/node-build#installation
      - mkdir -p "$(nodenv root)"/plugins
      - git clone https://github.com/nodenv/node-build.git "$(nodenv root)"/plugins/node-build

      - nodenv install -s
```

**Comment by fkorotkov** [comment] 2020-12-03 14:05
Closing as a duplicate of #379. In the meantime I can manually delete entry.

**Closed** 2020-12-03 14:05 UTC
Labels: feature

**Comment by AlexWayfer** [comment] 2020-12-03 16:14
> Closing as a duplicate of #379. In the meantime I can manually delete entry.

Sorry, thank you, didn't find it.
