### ISSUE TITLE
User is too new! Please check with support

### ISSUE THREAD

**Issue by vasnetsov** [cirruslabs/cirrus-ci-docs#977] opened 2022-02-20 14:51 UTC
## Expected Behavior

Build should start

## Real Behavior

Error "User is too new! Please check with support."

# Related Info

Trying to start build, but there is a bot protection or what. How long do I need to wait to be non-new user?

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.com/task/6461753612566528
- [ ] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment] 2022-02-20 15:25
Duplicate of #976

**Closed by fkorotkov** 2022-02-20 15:25 UTC
Labels: bug

**Comment by vasnetsov** [comment] 2022-02-20 15:28
@fkorotkov ok. Could you tell me how old user must be to build? Can't find anywhere.
