### ISSUE TITLE
macOS: Regular "Failed to clone because of a timeout from Git server!" 

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-ci-docs#1160] opened 2023-04-20 17:29 UTC
I can only find this example right now, but we've seen this a few times in the past weeks on macOS:
https://cirrus-ci.com/task/5474289692966912

edit: Here's another network failure (with a different error message):
https://cirrus-ci.com/task/6580115660865536

**Comment by fkorotkov** [comment] 2023-04-20 17:50
GitHub lately has a fair amount of incidents. We'll try to collect some data to see on which end the issue is.

In the meantime such failures should be automatically re-run. Do automatic re-runs succeed? Also don't hesitate to provide more links to failing tasks.

**Comment by real-or-random** [comment] 2023-04-20 18:00
Yes, re-runs typically succeed. It's just a bit annoying because there's a lot of scheduling pressure on macOS.  

Random idea: Perhaps it would be a useful optimization to retry just the clone command instead of the entire task?

**Comment by fkorotkov** [comment] 2023-04-20 18:05
Actually the agent should retry it. But seems it wasn't handling all the retriable cases. Fixing in https://github.com/cirruslabs/cirrus-ci-agent/pull/286

**Comment by fkorotkov** [comment] 2023-04-21 18:18
A retry was added and we also applied all the latest macOS and [Tart](https://github.com/cirruslabs/tart) updates. Please reopen if the issue persists.

**Comment by real-or-random** [comment] 2023-04-25 22:15
Here's another one that doesn't seem to be covered by the retry: https://cirrus-ci.com/task/4575075920248832

**Comment by edigaryev** [comment] 2023-05-01 06:33
The timeouts were not respected because the Persistent Worker was using a slightly outdated agent version (see "Agent logs" in the task's "Debugging View"), now it should be fixed.

**Closed by edigaryev** 2023-05-01 06:33 UTC
Labels: bug

**Comment by real-or-random** [comment] 2023-06-30 14:20
Here's another one that wasn't restarted: https://cirrus-ci.com/task/6316539322826752

**Comment by real-or-random** [comment] 2023-07-18 08:10
One more: https://cirrus-ci.com/task/6512232461238272
