### ISSUE TITLE
Manually trigger container via custom Dockerfile rebuild

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#476] opened 2019-10-02 19:54 UTC
In my project, I need to copy my requirements file and then install the specified dependencies, the problem is that when dependabot updates the requirements, the docker image isn’t rebuilt, meaning in-container deps aren’t up to date, and because of how big the dependency list is, we really can’t do it per-build. 
(This is for a private project)

**Comment by fkorotkov** [comment] 2019-10-02 20:16
Seems like a duplicate of #273

**Closed by fkorotkov** 2019-10-02 20:16 UTC
Labels: feature
