### ISSUE TITLE
Support uploading artifacts

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#168] opened 2019-02-25 16:42 UTC
Would love to see artifact uploading.  This means that you can upload certain files to the Cirrus CI servers which are stored for a limited time.  For example, if I build an EXE file of my project in the CI workspace, I can upload to Cirrus-ci.com for a limited time.  Additionally, (this part is just a proposal), you could pay extra for it to be hosted for longer periods of time.  They would be downloadable by anyone.  I can see big projects using this as a beta system.  
Thanks!

**Comment by fkorotkov** [comment] 2019-02-25 16:45
duplicate of #48

**Closed by fkorotkov** 2019-02-25 16:45 UTC
