### ISSUE TITLE
Unable to login to a second organization

### ISSUE THREAD

**Issue by rikur** [cirruslabs/cirrus-ci-docs#1082] opened 2022-10-12 15:48 UTC
I'm a member of multiple GitHub organizations and I can't seem to find a way to login to another one of those. I would like to register and pay for both organizations to use Cirrus CI.

**Comment by rikur** [comment] 2022-10-12 15:57
@fkorotkov Thank you for the insanely fast response. I can only see one organization under https://cirrus-ci.com/settings/profile/

However, I was hit by the GitHub incident while setting up another plan. Could this be the reason why I can't see the other organizations as well?

**Comment by rikur** [comment] 2022-10-12 15:58
While trying to setup a new plan, the GitHub marketplace says "Already setup" on the organization (which also got hit by the above mentioned incident).

**Comment by fkorotkov** [comment] 2022-10-12 16:00
Yes, the incident prevents you from the setup and therefore seeing it on the list. Sorry for the inconveniences! We have all reasons to believe it's the GH issue and we are waiting for a response.

The GitHub Marketplace thing and GitHub App installation are independent things so once the incident is resolved you'll be able to just install the App and everything will work.

**Comment by rikur** [comment] 2022-10-13 10:31
Still receiving `422 Unprocessable Entity`
<img width="744" alt="Screenshot 2022-10-13 at 11 29 38 am" src="https://user-images.githubusercontent.com/4004/195573841-aa846e9e-42f9-4c84-88b1-04e04a907a8e.png">

**Comment by rikur** [comment] 2022-10-13 10:37
FYI, I have created a support ticket on GH.

**Comment by fkorotkov** [comment] 2022-10-13 12:54
We've got some news from GH this morning. They acknowledge the issue and it's rare but not only affecting Cirrus CI App. Engineering team is looking into it so hopefully there will be a fix soon enough.

**Comment by rikur** [comment] 2022-10-13 17:07
Hopefully they'll fix it soon 🤞 Not sure if this is related, but /settings/profile gives me a blank page with the following errors.

<img width="617" alt="Screenshot 2022-10-13 at 6 06 04 pm" src="https://user-images.githubusercontent.com/4004/195661113-b4037ecb-19ea-43ae-8008-060d2f2448fa.png">
<img width="422" alt="Screenshot 2022-10-13 at 6 06 10 pm" src="https://user-images.githubusercontent.com/4004/195661128-28b09588-9da6-45c0-a9fd-117fc6cd5d94.png">

**Comment by fkorotkov** [comment] 2022-10-13 19:12
The NPE should be fixed now. That's just a front end bug caused by the issue but not the root cause. 😪

**Comment by fkorotkov** [comment] 2022-10-18 22:23
BTW it seems it's working now even though I haven't had a confirmation from GitHub.

**Closed by fkorotkov** 2022-10-18 22:23 UTC
Labels: question

**Comment by rikur** [comment] 2022-10-20 10:30
I got a confirmation from GitHub that the issue has been resolved!

However, the `/settings/profile` is empty. I'm only able to access the settings by going to a specific organization directly, which I luckily had in my browser history, e.g. `/settings/github/acmeinc`.

I can work with this for now, but maybe something worth checking out. Let me know if you need any further details.

**Comment by fkorotkov** [comment] 2022-10-20 19:16
@rikur could you please email support@cirruslabs.org with names of the organizations and we'll check it for you. I wonder if because of the incident there is an incomplete state in the DB.
