### ISSUE TITLE
Failed to prebuild container

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#434] opened 2019-08-29 19:56 UTC
# Expected Behavior

Docker image should have been pushed

# Real Behavior

https://cirrus-ci.com/task/5395444638679040

# Related Info

- [ ] Website issue
  - Link to page:
- [X] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name: push
  - Script/cache name (if applies): **gcloud**

**Comment by fkorotkov** [comment] 2019-08-29 20:29
Could you please try to re-run? I've been able to supply build a new container and push it. I wonder if it's a transient issue 🤔

**Comment by RDIL** [comment] 2019-08-29 21:42
Same issue @fkorotkov 
https://cirrus-ci.com/task/5990408808562688

**Comment by fkorotkov** [comment] 2019-08-29 22:15
Will try to reproduce it on your repository. BTW you can pass Gradle properties with ’-D’ through command line: https://docs.gradle.org/current/userguide/build_environment.html

**Comment by RDIL** [comment] 2019-08-30 00:20
Oh interesting, that eliminates this issue, but it still seems to be a bug so I won't close just yet.

**Comment by fkorotkov** [comment] 2019-09-13 16:13
Closing since the branch is gone and I'm unable to reproduce elsewhere. 😢

**Closed by fkorotkov** 2019-09-13 16:13 UTC
Labels: bug
