### ISSUE TITLE
Conda 4.10.0 and Linux Kernel "5.4.89+"

### ISSUE THREAD

**Issue by bjlittle** [cirruslabs/cirrus-ci-docs#837] opened 2021-04-07 13:59 UTC
# Issue

The adoption of the Linux Kernel `5.4.89+` by Cirrus-CI in combination with the recently released `conda` 4.10.0 within a Cirrus-CI Linux container results in the following `conda` traceback to the CI author:
```
InvalidVersionSpec: Invalid version '5.4.89+': empty version component
```
An associated issue has be raised with the `conda` developers, see https://github.com/conda/conda/issues/10596 to hopefully address this within `conda` i.e., being able to parse a poorly named Linux Kernel version string, where the `+` symbol is directly causing downstream issues.

### Steps to Reproduce
With any local installation of `conda` on Linux, to spoof the Linux Kernel version `5.4.89+`:
```shell
conda create -n conda4.10 conda=4.10
conda activate conda4.10
export CONDA_OVERRIDE_LINUX='5.4.89+'
conda update conda
```
See here to install [miniconda](https://docs.conda.io/en/latest/miniconda.html) for your local platform.

## Expected Behavior

What should have happened is that `conda` executes normally with the Linux Kernel version, and can `update` and `install` packages without issue.

## Real Behavior

What ended up happening was the (poorly) named Linux Kernel version `5.4.89+` causes major issues with `conda`.

This may be a wide-spread issue for the members of the Cirrus-CI community using Linux and `conda`. 

## Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS:
    - Linux (Kernel version `5.4.89+`)
  - Task name:
    - As an example, see https://cirrus-ci.com/build/4767977296887808

## Question

1. Can you share any immediate plans or milestones regarding the migration away from using Linux Kernel version `5.4.89+` on Cirrus-CI infra-structure?
1. How do you recommend best to share this issue with the wider Cirrus-CI community?
1. As a best practice, would it be possible not to adopt Linux Kernel versions with malformed version strings?

**Comment by fkorotkov** [comment] 2021-04-07 15:18
Cirrus always ran Linux containers on host with [Container-Optimized OS](https://cloud.google.com/container-optimized-os) which always had version ending with `+`. So it shouldn't be a new behaviour and seems like a concrete incompatibility with this particular conda version. I agree the version with `+` at the end is weird looking but it does comply with [semantic versioning](https://semver.org/):

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

You can workaround the issue by overriding the kernel for conda (copied from https://github.com/pletzer/mint/pull/32):

```console
export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
```

**Comment by bjlittle** [comment] 2021-04-07 15:38
Thanks @fkorotkov :+1: 

I'm rolling out my workaround from [pletzer/mint#32](https://github.com/pletzer/mint/pull/32) across all of our `cirrus-ci` enabled repos, of which there are a growing number.

It's good to know that you've always used `+` kernel versions, and that this is just evidence that `conda` needs to be able to cope with sematic version strings rather than just [pep-440](https://www.python.org/dev/peps/pep-0440/) version strings, which I'm guessing that they've only targeted as a use case.

**Comment by bjlittle** [comment] 2021-04-07 15:39
@fkorotkov I'm totally happy for you to close this issue now :+1: 

Also, thanks for `cirrus-ci`, it's pretty awesome :rocket: :partying_face: :tada:

**Comment by Minoru** [comment] 2021-04-07 15:40
@fkorotkov JFYI Linux doesn't follow semver ([Torvalds: "The version numbers are meaningless"](https://lkml.org/lkml/2018/4/15/201)), and AFAIK never did: 0.* days were chaos, 1.* too, 2.* days they had an odd-even numbering, and ever since 3.0 the scheme is essentially "bump whatever".

**Comment by bjlittle** [comment] 2021-04-07 15:41
Nice one.

Good to know @Minoru :+1:

**Comment by fkorotkov** [comment] 2021-04-07 16:01
@Minoru, thanks for the note!

I wasn't able to find an issue tracker for COS project to ask about the `+` in the version. But since it seems to be a regression on conda side I'm closing the issue in favor of the upstream issue https://github.com/conda/conda/issues/10596

**Closed by fkorotkov** 2021-04-07 16:01 UTC
Labels: bug

**Comment by bjlittle** [comment] 2021-04-07 16:35
@fkorotkov Thanks for cross posting on the associated `conda` issue - much appreciated :beers:

**Comment by fkorotkov** [comment] 2021-04-07 16:56
Sure thing! Thanks for raising the awareness. Glad you are enjoying Cirrus! 🍻
