### ISSUE TITLE
Clone fails on FreeBSD pull request

### ISSUE THREAD

**Issue by awnumar** [cirruslabs/cirrus-ci-docs#386] opened 2019-07-27 10:26 UTC
# Expected Behavior

Clone should have succeeded.

# Real Behavior

```
if ( "$CIRRUS_PR" == "" || ! $?CIRRUS_PR ) then
  git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
  git reset --hard $CIRRUS_CHANGE_IN_REPO
else
  git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
  git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
  git reset --hard $CIRRUS_CHANGE_IN_REPO
fi
/tmp/scriptsc64981855ad8681d0d86d1e91e001679.sh: 106: not found
/tmp/scriptsc64981855ad8681d0d86d1e91e001679.sh: 127CIRRUS_PR: not found
Cloning into '/tmp/go/src/github.com/awnumar/memguard'...
fatal: Remote branch pull/106 not found in upstream origin
Exit status: 128
```

# Related Info

https://cirrus-ci.com/task/5905078668492800

**Comment by fkorotkov** [comment] 2019-07-27 14:54
The issue is that Cirrus still uses `shell` to run scripts and not `tcsh`. Fixed in https://github.com/awnumar/memguard/pull/107

**Closed by fkorotkov** 2019-07-27 14:54 UTC
Labels: bug

**Comment by awnumar** [comment] 2019-07-27 15:38
Thank you very much for looking into this!

**Comment by awnumar** [comment] 2019-07-27 16:19
@fkorotkov This now fails on master. https://cirrus-ci.com/task/6307419716583424

**Comment by fkorotkov** [comment] 2019-07-27 19:31
@awnumar seems something weird with how the script is evaluated. Seems you can completely get rig of it though: https://github.com/awnumar/memguard/pull/108

**Comment by awnumar** [comment] 2019-07-27 20:54
Interesting. The builds seem to be faster now too which is a plus :) Thank you
